spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
---
spring:
  config:
    import: configserver:http://localhost:${CONFIG_SERVER_PORT:9149}
    activate:
      on-profile: localhost
---
spring:
  config:
    import: configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
    activate:
      on-profile: dev