spring:
  application:
    name: media-storage-query-service
---
spring:
  config:
    import: configserver:http://localhost:${CONFIG_SERVER_PORT:9149}
    activate:
      on-profile: localhost
---
spring:
  config:
    import: configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
    activate:
      on-profile: dev