server:
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
eureka:
  instance:
    prefer-ip-address: true

management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    env:
      post:
        enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${RMN_DB_HOST}:${RMN_DB_PORT:5432}/${RMN_BANK_INFO_DB:rmn_mobile_bank_info}
    username: ${RMN_DB_USER}
    password: ${RMN_DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT:9761}/eureka/

logging:
  file:
    name: ${RMN_LOG_DIR:log}/bank-info-service.log
---
server:
  port: ${BANK_INFO_PORT:9091}

spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/rmn_mobile_bank_info
    username: ${RMN_DB_USER:rmn_mobile}
    password: ${RMN_DB_USER:rmn_mobile}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:9761}/eureka/
